services:
  api:
    build: .
    container_name: llm-chat-api
    env_file:
      - .env
    ports:
      - "8001:8000"
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started
    networks:
      - llmnet
    # NO construir DATABASE_URL acá. Que venga en .env
    environment:
        - STUB_PROVIDER_MODE=${STUB_PROVIDER_MODE:-ok}

    #   DATABASE_URL: ${DATABASE_URL}

  postgres:
    image: postgres:16-alpine
    container_name: llm-chat-postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - llmnet

  redis:
    image: redis:7-alpine
    container_name: llm-chat-redis
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - llmnet
    ports:
      - "6380:6379"

networks:
  llmnet:

volumes:
  postgres_data:
